[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
lib_deps =
    adafruit/Adafruit DPS310 @ ^1.1.1
    adafruit/Adafruit BNO08x @ ^1.2.5
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
